LOCUS       NC_017660            5021812 bp    DNA     circular CON 24-APR-2023
DEFINITION  Escherichia coli KO11FL, complete sequence.
ACCESSION   NC_017660
VERSION     NC_017660.1
DBLINK      BioProject: PRJNA224116
            BioSample: SAMN02604168
            Assembly: GCF_000258025.1
KEYWORDS    RefSeq.
SOURCE      Escherichia coli KO11FL
  ORGANISM  Escherichia coli KO11FL
            Bacteria; Pseudomonadota; Gammaproteobacteria; Enterobacterales;
            Enterobacteriaceae; Escherichia.
REFERENCE   1  (bases 1 to 5021812)
  AUTHORS   Turner,P.C., Yomano,L.P., Jarboe,L.R., York,S.W., Baggett,C.L.,
            Moritz,B.E., Zentz,E.B., Shanmugam,K.T. and Ingram,L.O.
  TITLE     Optical mapping and sequencing of the Escherichia coli KO11 genome
            reveal extensive chromosomal rearrangements, and multiple tandem
            copies of the Zymomonas mobilis pdc and adhB genes
  JOURNAL   J Ind Microbiol Biotechnol 39 (4), 629-639 (2012)
   PUBMED   22075923
REFERENCE   2  (bases 1 to 5021812)
  AUTHORS   Turner,P.C., Yomano,L., Jarboe,L.R., Baggett,C.L., Moritz,B.,
            Zentz,E., Shanmugam,K.T. and Ingram,L.O.
  TITLE     Direct Submission
  JOURNAL   Submitted (01-AUG-2011) Microbiology and Cell Biology, University of
            Florida, Gainesville, FL 32611, USA
COMMENT     ##Genome-Annotation-Data-START##
            Annotation Provider               :: NCBI RefSeq
            Annotation Date                   :: 04/24/2023 01:04:54
            Annotation Pipeline :: NCBI Prokaryotic Genome Annotation Pipeline
            (PGAP)
            Annotation Method :: Best-placed reference protein set; GeneMarkS-2+
            Annotation Software revision      :: 6.5
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA
            Genes (total)                     :: 4,888
            CDSs (total)                      :: 4,769
            Genes (coding)                    :: 4,526
            CDSs (with protein)               :: 4,526
            Genes (RNA)                       :: 119
            rRNAs                             :: 8, 7, 7 (5S, 16S, 23S)
            complete rRNAs                    :: 8, 7, 7 (5S, 16S, 23S)
            tRNAs                             :: 85
            ncRNAs                            :: 12
            Pseudo Genes (total)              :: 243
            CDSs (without protein)            :: 243
            Pseudo Genes (ambiguous residues) :: 0 of 243
            Pseudo Genes (frameshifted)       :: 49 of 243
            Pseudo Genes (incomplete)         :: 182 of 243
            Pseudo Genes (internal stop)      :: 30 of 243
            Pseudo Genes (multiple problems)  :: 19 of 243
            Pseudo Genes (short protein)      :: 3 of 243
            CRISPR Arrays                     :: 2
            ##Genome-Annotation-Data-END##
            REFSEQ INFORMATION: The reference sequence is identical to
            CP002970.1.
            Genome was manually curated based on annotation generated by the
            NCBI Prokaryotic Genomes Automatic Annotation Pipeline Group.
            Information about the Pipeline can be found here:
            http://www.ncbi.nlm.nih.gov/genomes/static/Pipeline.html.
            Bacteria available from L.O. Ingram at the University of Florida,
            ingram@ufl.edu.
            The annotation was added by the NCBI Prokaryotic Genome Annotation
            Pipeline (PGAP). Information about PGAP can be found here:
            https://www.ncbi.nlm.nih.gov/genome/annotation_prok/
            COMPLETENESS: full length.
FEATURES             Location/Qualifiers
     source          1..5021812
                     /organism="Escherichia coli KO11FL"
                     /mol_type="genomic DNA"
                     /strain="KO11FL"
                     /db_xref="taxon:595495"
CONTIG      join(CP002970.1:1..5021812)
//
