LOCUS       NC_017664            4897452 bp    DNA     circular CON 24-APR-2023
DEFINITION  Escherichia coli W, complete sequence.
ACCESSION   NC_017664
VERSION     NC_017664.1
DBLINK      BioProject: PRJNA224116
            BioSample: SAMN02604169
            Assembly: GCF_000258145.1
KEYWORDS    RefSeq.
SOURCE      Escherichia coli W
  ORGANISM  Escherichia coli W
            Bacteria; Pseudomonadota; Gammaproteobacteria; Enterobacterales;
            Enterobacteriaceae; Escherichia.
REFERENCE   1  (bases 1 to 4897452)
  AUTHORS   Turner,P.C., Yomano,L.P., Jarboe,L.R., York,S.W., Baggett,C.L.,
            Moritz,B.E., Zentz,E.B., Shanmugam,K.T. and Ingram,L.O.
  TITLE     Optical mapping and sequencing of the Escherichia coli KO11 genome
            reveal extensive chromosomal rearrangements, and multiple tandem
            copies of the Zymomonas mobilis pdc and adhB genes
  JOURNAL   J Ind Microbiol Biotechnol 39 (4), 629-639 (2012)
   PUBMED   22075923
REFERENCE   2  (bases 1 to 4897452)
  AUTHORS   Turner,P.C., Yomano,L., Jarboe,L.R., Baggett,C.L., Moritz,B.,
            Zentz,E., Shanmugam,K.T. and Ingram,L.O.
  TITLE     Direct Submission
  JOURNAL   Submitted (29-JUL-2011) Microbiology and Cell Biology, University of
            Florida, Gainesville, FL 32611, USA
COMMENT     ##Genome-Annotation-Data-START##
            Annotation Provider               :: NCBI RefSeq
            Annotation Date                   :: 04/24/2023 01:47:43
            Annotation Pipeline :: NCBI Prokaryotic Genome Annotation Pipeline
            (PGAP)
            Annotation Method :: Best-placed reference protein set; GeneMarkS-2+
            Annotation Software revision      :: 6.5
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA
            Genes (total)                     :: 4,897
            CDSs (total)                      :: 4,778
            Genes (coding)                    :: 4,665
            CDSs (with protein)               :: 4,665
            Genes (RNA)                       :: 119
            rRNAs                             :: 8, 7, 7 (5S, 16S, 23S)
            complete rRNAs                    :: 8, 7, 7 (5S, 16S, 23S)
            tRNAs                             :: 87
            ncRNAs                            :: 10
            Pseudo Genes (total)              :: 113
            CDSs (without protein)            :: 113
            Pseudo Genes (ambiguous residues) :: 0 of 113
            Pseudo Genes (frameshifted)       :: 39 of 113
            Pseudo Genes (incomplete)         :: 65 of 113
            Pseudo Genes (internal stop)      :: 28 of 113
            Pseudo Genes (multiple problems)  :: 20 of 113
            Pseudo Genes (short protein)      :: 3 of 113
            CRISPR Arrays                     :: 2
            ##Genome-Annotation-Data-END##
            REFSEQ INFORMATION: The reference sequence is identical to
            CP002967.1.
            Genome was manually curated based on annotation generated by the
            NCBI Prokaryotic Genomes Automatic Annotation Pipeline Group.
            Information about the Pipeline can be found here:
            http://www.ncbi.nlm.nih.gov/genomes/static/Pipeline.html.
            The annotation was added by the NCBI Prokaryotic Genome Annotation
            Pipeline (PGAP). Information about PGAP can be found here:
            https://www.ncbi.nlm.nih.gov/genome/annotation_prok/
            COMPLETENESS: full length.
FEATURES             Location/Qualifiers
     source          1..4897452
                     /organism="Escherichia coli W"
                     /mol_type="genomic DNA"
                     /strain="W"
                     /culture_collection="ATCC:9637"
                     /db_xref="taxon:566546"
CONTIG      join(CP002967.1:1..4897452)
//
