LOCUS       NC_017656            5263980 bp    DNA     circular CON 23-FEB-2023
DEFINITION  Escherichia coli O55:H7 str. RM12579, complete sequence.
ACCESSION   NC_017656
VERSION     NC_017656.1
DBLINK      BioProject: PRJNA224116
            BioSample: SAMN02604278
            Assembly: GCF_000245515.1
KEYWORDS    RefSeq.
SOURCE      Escherichia coli O55:H7 str. RM12579
  ORGANISM  Escherichia coli O55:H7 str. RM12579
            Bacteria; Pseudomonadota; Gammaproteobacteria; Enterobacterales;
            Enterobacteriaceae; Escherichia.
REFERENCE   1  (bases 1 to 5263980)
  AUTHORS   Kyle,J.L., Cummings,C.A., Parker,C.T., Quinones,B., Vatta,P.,
            Newton,E., Huynh,S., Swimley,M., Degoricija,L., Barker,M.,
            Fontanoz,S., Nguyen,K., Patel,R., Fang,R., Tebbs,R., Petrauskene,O.,
            Furtado,M. and Mandrell,R.E.
  TITLE     Escherichia coli serotype O55:H7 diversity supports parallel
            acquisition of bacteriophage at Shiga toxin phage insertion sites
            during evolution of the O157:H7 lineage
  JOURNAL   J Bacteriol 194 (8), 1885-1896 (2012)
   PUBMED   22328665
REFERENCE   2  (bases 1 to 5263980)
  AUTHORS   Kyle,J.L., Cummings,C.A., Parker,C.T., Quinones,B., Vatta,P.,
            Newton,E., Huynh,S., Swimley,M.S., Degoricija,L., Barker,M.,
            Fontanoz,S., Nguyen,K., Patel,R., Fang,R., Tebbs,R., Petrauskene,O.,
            Furtado,M. and Mandrell,R.E.
  TITLE     Direct Submission
  JOURNAL   Submitted (09-NOV-2011) Western Regional Research Center / Produce
            Safety and Microbiology Research Unit, United States Department of
            Agriculture / Agricultural Research Service, 800 Buchanan Street,
            Albany, CA 94710, USA
COMMENT     ##Genome-Annotation-Data-START##
            Annotation Provider               :: NCBI RefSeq
            Annotation Date                   :: 02/23/2023 08:43:40
            Annotation Pipeline :: NCBI Prokaryotic Genome Annotation Pipeline
            (PGAP)
            Annotation Method :: Best-placed reference protein set; GeneMarkS-2+
            Annotation Software revision      :: 6.4
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA
            Genes (total)                     :: 5,348
            CDSs (total)                      :: 5,217
            Genes (coding)                    :: 4,977
            CDSs (with protein)               :: 4,977
            Genes (RNA)                       :: 131
            rRNAs                             :: 8, 7, 7 (5S, 16S, 23S)
            complete rRNAs                    :: 8, 7, 7 (5S, 16S, 23S)
            tRNAs                             :: 102
            ncRNAs                            :: 7
            Pseudo Genes (total)              :: 240
            CDSs (without protein)            :: 240
            Pseudo Genes (ambiguous residues) :: 0 of 240
            Pseudo Genes (frameshifted)       :: 93 of 240
            Pseudo Genes (incomplete)         :: 122 of 240
            Pseudo Genes (internal stop)      :: 70 of 240
            Pseudo Genes (multiple problems)  :: 40 of 240
            Pseudo Genes (short protein)      :: 4 of 240
            CRISPR Arrays                     :: 2
            ##Genome-Annotation-Data-END##
            REFSEQ INFORMATION: The reference sequence is identical to
            CP003109.1.
            Genome was manually curated based on annotation generated by the
            NCBI Prokaryotic Genomes Automatic Annotation Pipeline Group.
            Information about the Pipeline can be found here:
            http://www.ncbi.nlm.nih.gov/genomes/static/Pipeline.html.
            Bacteria available from Dr. Robert Mandrell
            (robert.mandrell@ars.usda.gov).
            The annotation was added by the NCBI Prokaryotic Genome Annotation
            Pipeline (PGAP). Information about PGAP can be found here:
            https://www.ncbi.nlm.nih.gov/genome/annotation_prok/
            COMPLETENESS: full length.
FEATURES             Location/Qualifiers
     source          1..5263980
                     /organism="Escherichia coli O55:H7 str. RM12579"
                     /mol_type="genomic DNA"
                     /strain="RM12579"
                     /serotype="O55:H7"
                     /isolation_source="urine from child < 5 years old"
                     /host="Homo sapiens"
                     /db_xref="taxon:1048689"
                     /country="USA: California"
                     /collection_date="1974-12"
CONTIG      join(CP003109.1:1..5263980)
//
