LOCUS       NC_017657              66078 bp    DNA     circular CON 23-FEB-2023
DEFINITION  Escherichia coli O55:H7 str. RM12579 plasmid p12579_2, complete
            sequence.
ACCESSION   NC_017657
VERSION     NC_017657.1
DBLINK      BioProject: PRJNA224116
            BioSample: SAMN02604278
            Assembly: GCF_000245515.1
KEYWORDS    RefSeq.
SOURCE      Escherichia coli O55:H7 str. RM12579
  ORGANISM  Escherichia coli O55:H7 str. RM12579
            Bacteria; Pseudomonadota; Gammaproteobacteria; Enterobacterales;
            Enterobacteriaceae; Escherichia.
REFERENCE   1  (bases 1 to 66078)
  AUTHORS   Kyle,J.L., Cummings,C.A., Parker,C.T., Quinones,B., Vatta,P.,
            Newton,E., Huynh,S., Swimley,M., Degoricija,L., Barker,M.,
            Fontanoz,S., Nguyen,K., Patel,R., Fang,R., Tebbs,R., Petrauskene,O.,
            Furtado,M. and Mandrell,R.E.
  TITLE     Escherichia coli serotype O55:H7 diversity supports parallel
            acquisition of bacteriophage at Shiga toxin phage insertion sites
            during evolution of the O157:H7 lineage
  JOURNAL   J Bacteriol 194 (8), 1885-1896 (2012)
   PUBMED   22328665
REFERENCE   2  (bases 1 to 66078)
  AUTHORS   Kyle,J.L., Cummings,C.A., Parker,C.T., Quinones,B., Vatta,P.,
            Newton,E., Huynh,S., Swimley,M.S., Degoricija,L., Barker,M.,
            Fontanoz,S., Nguyen,K., Patel,R., Fang,R., Tebbs,R., Petrauskene,O.,
            Furtado,M. and Mandrell,R.E.
  TITLE     Direct Submission
  JOURNAL   Submitted (09-NOV-2011) Western Regional Research Center / Produce
            Safety and Microbiology Research Unit, United States Department of
            Agriculture / Agricultural Research Service, 800 Buchanan Street,
            Albany, CA 94710, USA
COMMENT     ##Genome-Annotation-Data-START##
            Annotation Provider               :: NCBI RefSeq
            Annotation Date                   :: 02/23/2023 08:43:40
            Annotation Pipeline :: NCBI Prokaryotic Genome Annotation Pipeline
            (PGAP)
            Annotation Method :: Best-placed reference protein set; GeneMarkS-2+
            Annotation Software revision      :: 6.4
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA
            Genes (total)                     :: 5,348
            CDSs (total)                      :: 5,217
            Genes (coding)                    :: 4,977
            CDSs (with protein)               :: 4,977
            Genes (RNA)                       :: 131
            rRNAs                             :: 8, 7, 7 (5S, 16S, 23S)
            complete rRNAs                    :: 8, 7, 7 (5S, 16S, 23S)
            tRNAs                             :: 102
            ncRNAs                            :: 7
            Pseudo Genes (total)              :: 240
            CDSs (without protein)            :: 240
            Pseudo Genes (ambiguous residues) :: 0 of 240
            Pseudo Genes (frameshifted)       :: 93 of 240
            Pseudo Genes (incomplete)         :: 122 of 240
            Pseudo Genes (internal stop)      :: 70 of 240
            Pseudo Genes (multiple problems)  :: 40 of 240
            Pseudo Genes (short protein)      :: 4 of 240
            CRISPR Arrays                     :: 2
            ##Genome-Annotation-Data-END##
            REFSEQ INFORMATION: The reference sequence is identical to
            CP003111.1.
            Genome was manually curated based on annotation generated by the
            NCBI Prokaryotic Genomes Automatic Annotation Pipeline Group.
            Information about the Pipeline can be found here:
            http://www.ncbi.nlm.nih.gov/genomes/static/Pipeline.html.
            Bacteria available from Dr. Robert Mandrell
            (robert.mandrell@ars.usda.gov).
            The annotation was added by the NCBI Prokaryotic Genome Annotation
            Pipeline (PGAP). Information about PGAP can be found here:
            https://www.ncbi.nlm.nih.gov/genome/annotation_prok/
            COMPLETENESS: full length.
FEATURES             Location/Qualifiers
     source          1..66078
                     /organism="Escherichia coli O55:H7 str. RM12579"
                     /mol_type="genomic DNA"
                     /strain="RM12579"
                     /serotype="O55:H7"
                     /isolation_source="urine from child < 5 years old"
                     /host="Homo sapiens"
                     /db_xref="taxon:1048689"
                     /plasmid="p12579_2"
                     /country="USA: California"
                     /collection_date="1974-12"
     gene            51..452
                     /locus_tag="ECO55CA74_RS26945"
                     /old_locus_tag="ECO55CA74_25909"
     CDS             51..452
                     /locus_tag="ECO55CA74_RS26945"
                     /old_locus_tag="ECO55CA74_25909"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001198918.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="antirestriction protein"
                     /protein_id="WP_001198945.1"
                     /translation="MQYAKPVTLNVEECDSLSFLPYLFGLGFLYAEASVYALAKQMMPE
                     YEGGFWHFIRLPDGDRFHLVNGANWFDRTVSADAAGIILTSLVINRQLWLYHDSGDAGL
                     THLYRMRDAQSWSHIEVHPECNAIYAALD"
     gene            499..921
                     /locus_tag="ECO55CA74_RS26950"
                     /old_locus_tag="ECO55CA74_25914"
     CDS             499..921
                     /locus_tag="ECO55CA74_RS26950"
                     /old_locus_tag="ECO55CA74_25914"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052650.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DUF1380 family protein"
                     /protein_id="WP_000271758.1"
                     /translation="MYCTVKEIIREVLDTDVPDSECVFAVVLTRGDVRHIARDWSLTDD
                     ELETVMQRLDDAFEHGADVSIVHDVVRELMEEKRASRQVTVPAVMLEKVMALAGSEMKR
                     LYAVGSENGGDGDAFVREEREAMDVVLQALDGEHMS"
     gene            918..1109
                     /locus_tag="ECO55CA74_RS26955"
     CDS             918..1109
                     /locus_tag="ECO55CA74_RS26955"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_016238862.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_001024835.1"
                     /translation="MNINTETREILRNYRAVINARRREMGQKPLTTAQIVDEICDFVAN
                     QQAVFLGGHYILQGSRNR"
     gene            1608..1814
                     /locus_tag="ECO55CA74_RS32065"
                     /old_locus_tag="ECO55CA74_25919"
     CDS             1608..1814
                     /locus_tag="ECO55CA74_RS32065"
                     /old_locus_tag="ECO55CA74_25919"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000547968.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_000275846.1"
                     /translation="MYIPQKFLPKSRQKLLRSAPGQSFPAVAVMPLAAKVLKKVMVNTG
                     GNKRQVPAKRQNRGSRNSKDDGG"
     gene            1839..2126
                     /locus_tag="ECO55CA74_RS26975"
                     /old_locus_tag="ECO55CA74_25924"
     CDS             1839..2126
                     /locus_tag="ECO55CA74_RS26975"
                     /old_locus_tag="ECO55CA74_25924"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001825190.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_000107542.1"
                     /translation="MSTRNIHVNTASYTLLVAGKKKNTGEEWDVLEFSSLTELKKYRKS
                     HPEKMAFSYSYALSRGVDTQFRHINIAEADHFKQFLRQIKRAGLDIRAIC"
     gene            2245..3066
                     /locus_tag="ECO55CA74_RS26980"
                     /old_locus_tag="ECO55CA74_25929"
     CDS             2245..3066
                     /locus_tag="ECO55CA74_RS26980"
                     /old_locus_tag="ECO55CA74_25929"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001234456.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DUF932 domain-containing protein"
                     /protein_id="WP_001234472.1"
                     /translation="MRLASRFGRYNSIRRERPLTDDELMQFVPSVFSGDKHESRSERYT
                     YIPTINIINKLRDEGFQPFFACQSRVRDLGRREYSKHMLRLRREGHINGQEVPEIILLN
                     SHDGSSSYQMIPGIFRFVCTNGLVCGNNFGEIRVPHKGDIVGQVIEGAYEVLGVFDKVT
                     DNMEAMKEIHLNSDEQHLFGRAALMVRYEDENKTPVTPEQIITPRRRENKQNDLWTTWQ
                     RAQENMIKGGLSGRSASGKNTRTRAITGIDGDIRINKALWGIAEQFRKWKS"
     gene            3345..4685
                     /locus_tag="ECO55CA74_RS26985"
                     /old_locus_tag="ECO55CA74_25934"
     CDS             3345..4685
                     /locus_tag="ECO55CA74_RS26985"
                     /old_locus_tag="ECO55CA74_25934"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_012904641.1"
                     /GO_function="GO:0004803 - transposase activity [Evidence
                     IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="IS4 family transposase"
                     /protein_id="WP_001130323.1"
                     /translation="MPLLNDLLDFSDHPLMSQPSAQLFAEHLPVEWIQHCLTLSAHATV
                     RRRRLPGDMVIWMVVAMAFFRNEPITDVVRRLNLSADGEAGMNLLARSAVTQARQRVGA
                     APVEWLFRQTAQTWGSERYLKDDWHGLQLFAIDGAQFRTPDEPELREYYGSANTSTERQ
                     SAYPVMRLVALMNLGSHILLNAVTAPYRRRSETVLAHSMLATIPDNSITLFDKLFYSAD
                     LLLTLSQLGCNRHWLLPAWKNIAAETEESYGPGDRLLKLKVSLQARKKNPALPEFWYAR
                     AVTYEVNGMEKTVLTSLPADRYKAKEVAELYHSRWEIEVGFRNLKSSLLNNALVLRSRK
                     VELLEQEVWGMLLAYNLIRREATKAAEKHKKAASEISFKFAFQFIATEMIVLGNTASPG
                     TIPKRLEHLRGALEIVFITKRPRPSRPRAVKISKIRYPVKRSTAPLK"
     gene            complement(4806..5396)
                     /locus_tag="ECO55CA74_RS26990"
                     /old_locus_tag="ECO55CA74_25939"
     CDS             complement(4806..5396)
                     /locus_tag="ECO55CA74_RS26990"
                     /old_locus_tag="ECO55CA74_25939"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_020246007.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="transglycosylase SLT domain-containing protein"
                     /protein_id="WP_013009334.1"
                     /translation="MVRTTNLLSLFVEWVKLFTDKVTRGGKMKKWMLAICLMFINEICH
                     ATDCFDLAGRDYKIDPDLLRAISWKESRYRVNAIGINPVTGYGSGLMQVDSQHFNELAR
                     YGIKPEHLTTDPCMNIYTGAYYLAIAFKKWGVSWEAVGAYNAGFRKTEHQNQRRLAYAS
                     DVYRIYTGIKSSKGIRIPATKKSLPEINSVQNN"
     gene            5729..6112
                     /gene="traM"
                     /locus_tag="ECO55CA74_RS26995"
                     /old_locus_tag="ECO55CA74_25944"
     CDS             5729..6112
                     /gene="traM"
                     /locus_tag="ECO55CA74_RS26995"
                     /old_locus_tag="ECO55CA74_25944"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001151541.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="conjugal transfer relaxosome DNA-binding protein
                     TraM"
                     /protein_id="WP_001151524.1"
                     /translation="MAKVNLYISNDAYEKINAIIEKRRQEGAREKDVSFSATASMLLEL
                     GLRVHEAQMERKESAFNQTEFNKLLLECVVKTQSSVAKILGIESLSPHVSGNPKFEYAN
                     MVEDIREKVSSEMERFFPKNDDE"
     gene            6299..6988
                     /gene="traJ"
                     /locus_tag="ECO55CA74_RS31355"
                     /pseudo=""
     CDS             6299..6988
                     /gene="traJ"
                     /locus_tag="ECO55CA74_RS31355"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_003979562.1"
                     /note="internal stop; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="conjugal transfer transcriptional regulator TraJ"
     gene            7081..7482
                     /gene="traY"
                     /locus_tag="ECO55CA74_RS27005"
                     /old_locus_tag="ECO55CA74_25954"
     CDS             7081..7482
                     /gene="traY"
                     /locus_tag="ECO55CA74_RS27005"
                     /old_locus_tag="ECO55CA74_25954"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_012006553.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="conjugal transfer relaxosome DNA-bindin protein
                     TraY"
                     /protein_id="WP_225877511.1"
                     /translation="MLLKRFGTRSATGKMVKLKLPVDVESLLIEASNRSGRSRSFEAVI
                     RLKDHLHRYPKFNRAGNIYDKSLVKYLTMRLDDETNQLLIAAKNRSGWCKTDEAADRVI
                     DHLIKFPDFYDSEIFREADKEEDITFNTL"
     gene            7515..7879
                     /gene="traA"
                     /locus_tag="ECO55CA74_RS27010"
                     /old_locus_tag="ECO55CA74_25959"
                     /pseudo=""
     CDS             7515..7879
                     /gene="traA"
                     /locus_tag="ECO55CA74_RS27010"
                     /old_locus_tag="ECO55CA74_25959"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001401864.1"
                     /note="frameshifted; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="type IV conjugative transfer system pilin TraA"
     gene            7894..8205
                     /gene="traL"
                     /locus_tag="ECO55CA74_RS27015"
                     /old_locus_tag="ECO55CA74_25964"
     CDS             7894..8205
                     /gene="traL"
                     /locus_tag="ECO55CA74_RS27015"
                     /old_locus_tag="ECO55CA74_25964"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_490564.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type IV conjugative transfer system protein TraL"
                     /protein_id="WP_000012106.1"
                     /translation="MSGDENKLKKYRFPETLTNQSRWFGLPLDELIPAAICIGWGITTS
                     KYLFGIGAAVLVYFGIKKLKKGRGSSWLRDLIYWYMPTALLRGIFHNVPDSCFRQWIK"
     gene            8227..8793
                     /gene="traE"
                     /locus_tag="ECO55CA74_RS27020"
                     /old_locus_tag="ECO55CA74_25969"
     CDS             8227..8793
                     /gene="traE"
                     /locus_tag="ECO55CA74_RS27020"
                     /old_locus_tag="ECO55CA74_25969"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_490565.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type IV conjugative transfer system protein TraE"
                     /protein_id="WP_000399770.1"
                     /translation="MEHGARLSTSRVMAIAFIFISVLIVLSLSVNVIQGVNNYRLQNEQ
                     RTAVTPMAFNAPFAMSQNSADASYLQQMALSFIALRLNVSSETVDASHQALLQYIRPGA
                     QNQMKVILAEEAKRIKNDNVNSAFFQTSVRVWPQYGRVEIRGVLKTWIGDSKPFTDIKH
                     YILILKRENGVTWLDNFGETDDEKK"
     gene            8780..>9280
                     /gene="traK"
                     /locus_tag="ECO55CA74_RS27025"
                     /old_locus_tag="ECO55CA74_25974"
                     /pseudo=""
     CDS             8780..>9280
                     /gene="traK"
                     /locus_tag="ECO55CA74_RS27025"
                     /old_locus_tag="ECO55CA74_25974"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001230803.1"
                     /note="incomplete; partial in the middle of a contig;
                     missing C-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="type-F conjugative transfer system secretin TraK"
     gene            <9308..>10057
                     /locus_tag="ECO55CA74_RS27030"
                     /old_locus_tag="ECO55CA74_25979"
                     /pseudo=""
     CDS             <9308..>10057
                     /locus_tag="ECO55CA74_RS27030"
                     /old_locus_tag="ECO55CA74_25979"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_490592.1"
                     /note="cleaves origin of transfer and unwinds; oriT
                     relaxase; incomplete; partial in the middle of a contig;
                     missing N-terminus and C-terminus; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="conjugative transfer relaxase/helicase TraI"
     gene            10072..10518
                     /locus_tag="ECO55CA74_RS27035"
                     /old_locus_tag="ECO55CA74_25984"
     CDS             10072..10518
                     /locus_tag="ECO55CA74_RS27035"
                     /old_locus_tag="ECO55CA74_25984"
                     /inference="COORDINATES: ab initio prediction:GeneMarkS-2+"
                     /note="Derived by automated computational analysis using
                     gene prediction method: GeneMarkS-2+."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_001150980.1"
                     /translation="MQDGVRIARDNPDSGVVVRIAGEGRPWNPSAITGGRVWGDIPDNS
                     VQPGAGNGEPVTAEVLAQRQAEEAIRRETERRADEIVRKMAENKPDLPDGKTEQAVREI
                     AGQERDRAAITEREAALLESVLRESQRERDMVRDLQKEKTLGGD"
     gene            10538..11284
                     /gene="traX"
                     /locus_tag="ECO55CA74_RS27040"
                     /old_locus_tag="ECO55CA74_25989"
     CDS             10538..11284
                     /gene="traX"
                     /locus_tag="ECO55CA74_RS27040"
                     /old_locus_tag="ECO55CA74_25989"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052669.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="conjugal transfer pilus acetylase TraX"
                     /protein_id="WP_000205758.1"
                     /translation="MTTDNTNTTRNDSLAARTDTWLQSLLVWSPGQRDIIKTVALVLMV
                     LDHANRILHLDQTWMFLAGRGAFPLFALVWGLNLSRHAHIRQSAINRLWGWAVFSQFWY
                     YFAGFTWYEGNILFAFAVAAQVLTWCETRSGWRTAAAILMMALWGPLSGTSYGIAGLLM
                     LAVSHRLYRAEDRTERLALVACLLAVIPALNLASCDVAAVAGLVMTVLTVGLVSCTGKS
                     LPRFWPGDFFPTFYACHLAVLGVLAL"
     gene            11339..11899
                     /locus_tag="ECO55CA74_RS27045"
                     /old_locus_tag="ECO55CA74_25994"
     CDS             11339..11899
                     /locus_tag="ECO55CA74_RS27045"
                     /old_locus_tag="ECO55CA74_25994"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_858384.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="fertility inhibition protein FinO"
                     /protein_id="WP_000139371.1"
                     /translation="MTEQKRPVLTLKRKTEGTGPVRSRKTIINVTTPQKWKVKKQKLAE
                     KAAREAELAAKKAQARQALSIYLTLPSLDEAVNTLKPWWPGLFDGDTPRLLACGIRDVL
                     LEDVVQRNIPLSHKKLRRALKAITRSESYLCAMKAGACRYDTEGYVTEHISQEEEAYAA
                     ERLDKIRRQNRIKAELQAVLDEK"
     gene            12034..12239
                     /locus_tag="ECO55CA74_RS27050"
                     /old_locus_tag="ECO55CA74_25999"
                     /pseudo=""
     CDS             12034..12239
                     /locus_tag="ECO55CA74_RS27050"
                     /old_locus_tag="ECO55CA74_25999"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_858385.1"
                     /note="frameshifted; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
     gene            12485..>12834
                     /locus_tag="ECO55CA74_RS27055"
                     /old_locus_tag="ECO55CA74_26004"
                     /pseudo=""
     CDS             12485..>12834
                     /locus_tag="ECO55CA74_RS27055"
                     /old_locus_tag="ECO55CA74_26004"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052672.1"
                     /note="frameshifted; incomplete; partial in the middle of a
                     contig; missing C-terminus; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="thermonuclease family protein"
     gene            complement(13242..>13385)
                     /locus_tag="ECO55CA74_RS31360"
                     /pseudo=""
     CDS             complement(13242..>13385)
                     /locus_tag="ECO55CA74_RS31360"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_076611434.1"
                     /note="incomplete; partial in the middle of a contig;
                     missing N-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="IS3 family transposase"
     gene            complement(<13388..13531)
                     /locus_tag="ECO55CA74_RS27060"
                     /old_locus_tag="ECO55CA74_26009"
                     /pseudo=""
     CDS             complement(<13388..13531)
                     /locus_tag="ECO55CA74_RS27060"
                     /old_locus_tag="ECO55CA74_26009"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_076611553.1"
                     /note="incomplete; partial in the middle of a contig;
                     missing C-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="IS3 family transposase"
     gene            <13609..14282
                     /locus_tag="ECO55CA74_RS29820"
                     /pseudo=""
     CDS             <13609..14282
                     /locus_tag="ECO55CA74_RS29820"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_012477168.1"
                     /GO_process="GO:0015074 - DNA integration [Evidence IEA]"
                     /note="frameshifted; internal stop; incomplete; partial in
                     the middle of a contig; missing N-terminus; Derived by
                     automated computational analysis using gene prediction
                     method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="DDE-type integrase/transposase/recombinase"
     gene            14784..17444
                     /locus_tag="ECO55CA74_RS27075"
                     /old_locus_tag="ECO55CA74_26024"
     CDS             14784..17444
                     /locus_tag="ECO55CA74_RS27075"
                     /old_locus_tag="ECO55CA74_26024"
                     /EC_number="3.4.24.-"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052607.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="M66 family glycomucinase StcE"
                     /protein_id="WP_000770129.1"
                     /translation="MKLKYLSCMILASLAMGAFAATAADNNSAIYFNTTQPVNDLQGGL
                     AAEVKFAQSQILSAHPKEGESQQHLTSLRKSLLLVRLVKADDKTPVQVEARDANDKILG
                     TLTLSPPSSLPDTVYHLDGVPADGIDFTPQNGTKKIINTVAEVNKLSDASGSSIKSYLA
                     NNALVEIQTANGRWIRDMYLPQGAELEGKMVRFVSYAGYNSTVFYGDRKVTLSVGNTLL
                     FKYVNGQWFRSGELENNRIAYAQHTWSAELPAHWIVPGLNLVIKQGNLSGSLNDINVGA
                     PGELLLHTIDIGMLTTPRGRFDFAKDKEAHREYFQTIPVSRMIVNNYAPLHLKEVMLPT
                     GTLLTDADPGEGGWHSGTMRQSIGKELISHGIDNANYGINSTAGSGESSHPYVAAQLTA
                     HTNRGNYSNGVQVHGGSGGGGIVTLDSTLGNEFSHEVGHNFGLGHYVGGFRGSVHRSAD
                     QINSTWGWDSDKKRFIPNFYPAQTNRKSCLDEQCQEPFDGHSFGFDAMAGGSPFSDANR
                     FTMYTPNSSAIIQRFFENKAVFDSLSSTGFSKWNADEHKMEPYEHTIDRFEQITASVRD
                     LSENKMAEMMAEYPIVKVHMSDGNWTRDIHAPAASAENKGRILTLDHEAGYNSHLFING
                     GEKIISKGYKKSFVSDGQTWKESDVVNTREARKPEKFGVPVTTLVGYYDPKGTLSSFIY
                     PAMYGAYGFTYSDDSENLSSNDCQLQVDTREGQLRFKLANNRVNSSVMNKFHINVPTES
                     QPTQAILVCNNKVLDTRTLTPAPEGLTYTVNGRALPAKENEGCIVSVKTAQRYCLPVGQ
                     RSGSRLPDWIAGQEVYVDSGAKAKVLLSDWDNLSYNRIGEFVGNVNPADMKKVKAWNGQ
                     YLDFSRPRSMRVVNK"
     gene            17528..18403
                     /gene="gspC"
                     /locus_tag="ECO55CA74_RS27080"
                     /old_locus_tag="ECO55CA74_26029"
     CDS             17528..18403
                     /gene="gspC"
                     /locus_tag="ECO55CA74_RS27080"
                     /old_locus_tag="ECO55CA74_26029"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052608.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system protein GspC"
                     /protein_id="WP_001368871.1"
                     /translation="MLFFLSSRRDRNLFIKDIALKMLTPNWVLCVILLIAGYQLVSVIR
                     HFWLTPATSASDLSHVSVSETAVTDEHTEENFVFTLFGTASPPLSEGKVQKTTSSLSDD
                     LLSGGDLDVRGILYSSVTEHSVAIFAHNNRQFSLGIGEKVPGYDATISAIFSDHIVINY
                     QGKNASLPLRYDNPAKRNAQDDNNLIVGPVTTQANFRVKNIFDIMSLSPVTVNNTLSGY
                     RLSPGKASSLFYNAGLHDNDLAVLLNGSELRDTRQAKQIMKQLTELKEIKITVERDGQL
                     YDAFIAVGEN"
     gene            18404..20374
                     /gene="etpD"
                     /locus_tag="ECO55CA74_RS27085"
                     /old_locus_tag="ECO55CA74_26034"
     CDS             18404..20374
                     /gene="etpD"
                     /locus_tag="ECO55CA74_RS27085"
                     /old_locus_tag="ECO55CA74_26034"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001368872.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="variant type II secretion system secretin EtpD"
                     /protein_id="WP_013009342.1"
                     /translation="MFRKWLNGRLSVFVFTTVFLSAIPGWGAEFSASFKDTDIQEFINT
                     VSKNLHKTVIINPDVQGTITVRSYDMLNEEQYYQFFLSVLDVYGFAVVDMHNGILKVVR
                     SKDAKTSAVPVASDASPGTGDEVVTRVVPVSNVAARDLAPLLRQLNDNAGAGSVVHYEP
                     SNVLLMTGRAAVMKRLMEIVERVDKEGNRSVATVPLTYASATDVARLVTELTKESDKTA
                     MPAWMTAKLVADERTNSVLVSGEPISQQRIISMIKQLDRKEDVQGNTKVIYLKYAKAKD
                     LVEVLTGISSNIENDAKKSSSTEALRKGVTIKSHEQTNALILTGAPDVIRDLENVISQL
                     DIRRPQVLVEAIIAEVQDADGLNLGIQWVNKHSGVTQFTSTGLPITTMVQTRQSDISDS
                     DQSNTLSMFNGIAAGFYQGNWAMLLTALSTSSKNDILATPSIVTLDNMEATFNVGQEVP
                     VLSGSQTTSGDNIFNTVERKTVGIKLRVKPQINEGDSVLLEIEQEVSGVADTAVATTTD
                     LGATFNTRTVTNAMLVGNGETVVVGGLLDKSIRGSESKVPLLGDIPVLGHLFSSKSEHA
                     AKRNLMLFIRPTIIRERDGFRHASAEKYLSFNQEQVQSRGKETMALTLNEEQLKLSRDR
                     DDTTFRKVKTAIAAFYARGMQ"
     gene            20371..21873
                     /gene="gspE"
                     /locus_tag="ECO55CA74_RS27090"
                     /old_locus_tag="ECO55CA74_26039"
     CDS             20371..21873
                     /gene="gspE"
                     /locus_tag="ECO55CA74_RS27090"
                     /old_locus_tag="ECO55CA74_26039"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052610.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system ATPase GspE"
                     /protein_id="WP_001418198.1"
                     /translation="MSSIQNVSESRPLLPFSFSRTQRILLLREQEGNQVFCMEDTPASA
                     LLEVRRVAEGPLNVTTLSAEAFEKQLVSCYQRDSDEARQMMADIGNEMDFYTVAGELPD
                     SEDLLDANDDAPIIRLINAMLTEAIKEKASDIHIETYERHLQVRFRVDGVLREILRLRR
                     NLASLLISRIKVMARLDIAEKRVPQDGRMVLRIGGRAVDVRVSTLPSNHGERIVLRLLD
                     KNSVSLDLAALGMSPQNQRHIDALIRRPHGIILVTGPTGSGKSTTLYAALSRLNPQDRN
                     IMTVEDPVEYELDGISQTQVNPKVDMTFARSLRAILRQDPDVVLVGEIRDSETAQIAVQ
                     ASLTGHLVLSTLHTNSAAGALSRLQDMGIPPFLLSTSLLAVLAQRLVRTLCPRCRQSCQ
                     ASAELAKDMDIPPETTIWQPAGCQHCSFTGYHGRTGLHELLLIDDRIRTAIYQGEGELS
                     ITRLAGGRYLTLRGDGRQKVLAGETSWEEVVRVTESRLQEEE"
     gene            21875..23098
                     /gene="gspF"
                     /locus_tag="ECO55CA74_RS27095"
                     /old_locus_tag="ECO55CA74_26044"
     CDS             21875..23098
                     /gene="gspF"
                     /locus_tag="ECO55CA74_RS27095"
                     /old_locus_tag="ECO55CA74_26044"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_004151937.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system inner membrane protein
                     GspF"
                     /protein_id="WP_001173149.1"
                     /translation="MALFHYQASDIHGRKRRGVLEADSARHARQLLREQALIPVRLEEK
                     QLHHQHSPRSILRFRPRGVSSAELALLTRQLSTLVAASLPLEEALDALSRQSEKPRQRD
                     LIAAVRARVLEGHSLATAMGMFPGTFERLYCAMVAAGETSGRLDVVLSRLADYTEQRQI
                     MRNRLLQALIYPCVLTLVAVGVIAILLTAVVPKVVEQFIHMKQTLPLSTRVLMGLTEVC
                     QTWGPWLLLAAATGWIAGRMMLHKPSRRLAFHHLLLRLPIVGRISRGLNTARYARTLSI
                     LNASAVPLLQAMYISGDVLSNDWARHQLATAAELVREGVSLHQALEQTSLFPSMMRHMI
                     ASGENSGELDSMLERAADNQDREFSAQMQLALGLFEPMLVVGMAGVVLFIVLAILQPLL
                     QLNNMMNI"
     gene            23129..23563
                     /gene="gspG"
                     /locus_tag="ECO55CA74_RS27100"
                     /old_locus_tag="ECO55CA74_26049"
     CDS             23129..23563
                     /gene="gspG"
                     /locus_tag="ECO55CA74_RS27100"
                     /old_locus_tag="ECO55CA74_26049"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052612.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system major pseudopilin GspG"
                     /protein_id="WP_001231213.1"
                     /translation="MRKQHQRGFTLLEIMVVIVILGVLASLVVPNLMGNKDKADRQKVV
                     SDLVALESALDMYRLDNNRYPTTEQGLRALVSKPTVQPEPRNYRQDGYIRRLPQDPWGG
                     DYQLLNPGQYSNIDIFSPGPDGIPNTEDDIGNWTPGHTQP"
     gene            23560..24111
                     /gene="gspH"
                     /locus_tag="ECO55CA74_RS27105"
                     /old_locus_tag="ECO55CA74_26054"
     CDS             23560..24111
                     /gene="gspH"
                     /locus_tag="ECO55CA74_RS27105"
                     /old_locus_tag="ECO55CA74_26054"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052613.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system minor pseudopilin GspH"
                     /protein_id="WP_000082928.1"
                     /translation="MSQRGFTILEMMLILLLMGITAGLVLMSFPDSAQNHLQQQRERLQ
                     AQLDYALDRSMQDGLLIGIQVRSDGWTFKVLQRVTAESFPASVGGDVWQGYVWQTWQPR
                     RAAMEGKLPDDVRLDLQYLRGLQWMPEHNDGTGPDILLLPGGEVTPFSLLFRLVGGEAV
                     TGLQVDENGLMTLFEGEVEL"
     gene            24126..24473
                     /gene="gspI"
                     /locus_tag="ECO55CA74_RS27110"
                     /old_locus_tag="ECO55CA74_26059"
     CDS             24126..24473
                     /gene="gspI"
                     /locus_tag="ECO55CA74_RS27110"
                     /old_locus_tag="ECO55CA74_26059"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052614.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system minor pseudopilin GspI"
                     /protein_id="WP_001420206.1"
                     /translation="MTLLEVMVALVVFALAGIALIQSTTQQAAGIGPMEEKVLAGWLAD
                     NQMVQLQLEKIWPKNGWDEKTISFAGREWYLRWHGRDSDIPQQRILEVEVRRTREETSA
                     LVSLRGSVVRE"
     gene            24470..25069
                     /gene="gspJ"
                     /locus_tag="ECO55CA74_RS27115"
                     /old_locus_tag="ECO55CA74_26064"
     CDS             24470..25069
                     /gene="gspJ"
                     /locus_tag="ECO55CA74_RS27115"
                     /old_locus_tag="ECO55CA74_26064"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052615.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system minor pseudopilin GspJ"
                     /protein_id="WP_000082784.1"
                     /translation="MSQQRVKGFTLLEMLLALAVFAALSISAFQVLQSGIRAHELSQDK
                     VRRLAELQRGGSQIERDLMQMIPRHSRGSEGLLLAAPHLLKSDDWGISFTRNSWLNPAG
                     MLPRPELQWVGYRLRQQKLERLSYFYVDHPSGIAPDVRVVLEGVHAFRLRFFVNGTWQA
                     RWDSTSILPQAVEVTLVMDDFAELTRLFLVSKETAE"
     gene            25066..26043
                     /gene="gspK"
                     /locus_tag="ECO55CA74_RS27120"
                     /old_locus_tag="ECO55CA74_26069"
     CDS             25066..26043
                     /gene="gspK"
                     /locus_tag="ECO55CA74_RS27120"
                     /old_locus_tag="ECO55CA74_26069"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052616.1"
                     /GO_component="GO:0016020 - membrane [Evidence IEA]"
                     /GO_process="GO:0009306 - protein secretion [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system minor pseudopilin GspK"
                     /protein_id="WP_000842183.1"
                     /translation="MKSREQGVALLVVLLILSLMVTIAAAIAERNGRTFWRTVAQLDQL
                     QAKWDGYSAEEMAIQILQRSRQASPRKTHLAQNWAQSELQFETGGGDVRGRIVDAQACF
                     NLNAINYGAVDLAGVPYAARIFQQLLINLQVDIIQARQVTAALRDWIDRDDEPVKGGAE
                     DEVYMGMEPPYLAASQPMQDVSELRLIRGIDVRLYRKLLPYVCVLPTSDLSVNVNTLLD
                     SQAPLLAALFLTKPNSLLVTKLLLRRPRTGWDSVAAFLDSPQLKGIDTSTAISVLAVSS
                     NYFLVRLHVRSGEHLFSQQTLMQWREERFRSIQRQYGLTVREVP"
     gene            25977..27254
                     /gene="gspL"
                     /locus_tag="ECO55CA74_RS27125"
                     /old_locus_tag="ECO55CA74_26074"
     CDS             25977..27254
                     /gene="gspL"
                     /locus_tag="ECO55CA74_RS27125"
                     /old_locus_tag="ECO55CA74_26074"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_012816828.1"
                     /GO_component="GO:0015627 - type II protein secretion
                     system complex [Evidence IEA]"
                     /GO_process="GO:0015628 - protein secretion by the type II
                     secretion system [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system protein GspL"
                     /protein_id="WP_225877510.1"
                     /translation="MERGAFPEHSATVWINGEGGTLNKNNKHVEAGRLFLRLPEDDTQP
                     LLWRLVSPEETGGGSVAVGETDPLLAGLLPRYPAWVLVPSDRIAFHQVTLPHRTWRQRL
                     QVLPFLLEEQLATDIEQLHFAILHQTGGRCNVAVVEKSVMHHWLTYCGQLGVREVRLLP
                     DVLMLPLATEGWSAVRLAGQWLFRSDRYAGMTVELSWLTQFLSLTAPPVIESYSVPPAQ
                     CMGLETTEWRAQPVRDLLQLAAECEGYDGADLRQGIFARQGTWYARFRPWRYVAGALLA
                     CVFLAGSNAGLAHYRLWQQAEFWQHESVRVYQELFPGETVVKDPHRQMLRHLQQSTSNN
                     MPELGGVMHQLQQLLPETSTIRLQALAWDSSSQTLKIDLQAASFQALEHFQQSAGEKYI
                     IQPGEIRQQPHGVESRLILRMNNERS"
     gene            27241..27756
                     /locus_tag="ECO55CA74_RS27130"
                     /old_locus_tag="ECO55CA74_26079"
     CDS             27241..27756
                     /locus_tag="ECO55CA74_RS27130"
                     /old_locus_tag="ECO55CA74_26079"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000998852.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II secretion system protein M"
                     /protein_id="WP_000998852.1"
                     /translation="MNDLKKRLQYISPRERRLLTGCVALLVVAFVYYVFWLPWQVREDK
                     WRTVIAREKYTVEWMKQQIPSIKKWEASMPEQGEPLGLSAAVTQTSAAYGVSVTRLQPQ
                     GERLTVTLAPVEFNTLMQWLTQLHRRYRIRTVVFDVVAQGNQPGHVTVNRLVLSRDDIN
                     RDTSPGHL"
     gene            27925..28641
                     /locus_tag="ECO55CA74_RS27135"
                     /old_locus_tag="ECO55CA74_26084"
     CDS             27925..28641
                     /locus_tag="ECO55CA74_RS27135"
                     /old_locus_tag="ECO55CA74_26084"
                     /EC_number="3.4.23.-"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052619.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="A24 family peptidase"
                     /protein_id="WP_231454492.1"
                     /translation="MLERRWRREALMLLAHSEPESEPVFNLMIPRSHCPYCFQPLSIRD
                     NIPLLSYLFLKGKSRCCGERIPIYYPLVEITSSVLFILAASRFHPGLTLVAAWLFIAML
                     LVLAVIDCRTAMLPDVLTLSLLWLGLLFSLQGGSVPLEEAVVGAVSGYLCLWGLYWLFR
                     FVTGREGLGYGDFKLAAALGAWMGWQVLPSVLLFASVSGLIITVLLRFVTATDFTRPLP
                     FGPWLALSGVCHFLLM"
     gene            28735..29136
                     /gene="eptO"
                     /locus_tag="ECO55CA74_RS27140"
                     /old_locus_tag="ECO55CA74_26089"
                     /gene_synonym="gspS"
     CDS             28735..29136
                     /gene="eptO"
                     /locus_tag="ECO55CA74_RS27140"
                     /old_locus_tag="ECO55CA74_26089"
                     /gene_synonym="gspS"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001222321.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="GspS family T2SS pilot lipoprotein variant EptO"
                     /protein_id="WP_001222321.1"
                     /translation="MRINTLKKLNCITSLLVLVTVAGCHQVPSTRKQATVPPSEQLEQT
                     ASIAAATRYLKRRCNRSDLPDDQAILNGVNRIANGKGWQFLTQEDIRKHSDEINERLAR
                     DSTPEHIKCSEFNRLLVPFIGELLAGTSR"
     gene            29262..>29426
                     /locus_tag="ECO55CA74_RS30750"
                     /pseudo=""
     CDS             29262..>29426
                     /locus_tag="ECO55CA74_RS30750"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_076612086.1"
                     /note="incomplete; partial in the middle of a contig;
                     missing C-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="IS3 family transposase"
     gene            complement(29380..29604)
                     /locus_tag="ECO55CA74_RS32550"
                     /old_locus_tag="ECO55CA74_26094"
     CDS             complement(29380..29604)
                     /locus_tag="ECO55CA74_RS32550"
                     /old_locus_tag="ECO55CA74_26094"
                     /inference="COORDINATES: protein motif:HMM:NF013698.2"
                     /GO_function="GO:0003677 - DNA binding [Evidence IEA];
                     GO:0004803 - transposase activity [Evidence IEA]"
                     /GO_process="GO:0006313 - transposition, DNA-mediated
                     [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="transposase"
                     /protein_id="WP_001368889.1"
                     /translation="MPLTGDIKGKIKTRKLKNTADAAKTVAEWLKKQSSELNEVHIIME
                     ATGVYHEPLAYGLHFAGAQWQLVHHYRSR"
     gene            <29725..30018
                     /locus_tag="ECO55CA74_RS31930"
                     /pseudo=""
     CDS             <29725..30018
                     /locus_tag="ECO55CA74_RS31930"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_858390.1"
                     /note="frameshifted; internal stop; incomplete; partial in
                     the middle of a contig; missing N-terminus; Derived by
                     automated computational analysis using gene prediction
                     method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
     gene            30247..30495
                     /gene="repA"
                     /locus_tag="ECO55CA74_RS27155"
                     /old_locus_tag="ECO55CA74_26099"
     CDS             30247..30495
                     /gene="repA"
                     /locus_tag="ECO55CA74_RS27155"
                     /old_locus_tag="ECO55CA74_26099"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000083832.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="replication regulatory protein RepA"
                     /protein_id="WP_000083841.1"
                     /translation="MSQTENAVTSSSGTKRAYRKGNPLTLAERQQASLARKRATHKELR
                     VFIPAALKVQLQEMCEAEGVTQAEMIAELIKQKSAFS"
     gene            <30518..30625
                     /locus_tag="ECO55CA74_RS32070"
                     /pseudo=""
     CDS             <30518..30625
                     /locus_tag="ECO55CA74_RS32070"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052675.1"
                     /note="RepA; incomplete; partial in the middle of a contig;
                     missing N-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="incFII family plasmid replication initiator RepA"
     gene            31326..31484
                     /locus_tag="ECO55CA74_RS31935"
                     /old_locus_tag="ECO55CA74_26104"
     CDS             31326..31484
                     /locus_tag="ECO55CA74_RS31935"
                     /old_locus_tag="ECO55CA74_26104"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001700046.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_000829588.1"
                     /translation="MAENGYGLAGLGMGKVKSINQYRLTPGFGGFTPVSHVTTACRLPC
                     RWRGISW"
     gene            31539..31808
                     /gene="yacA"
                     /locus_tag="ECO55CA74_RS27165"
                     /old_locus_tag="ECO55CA74_26109"
     CDS             31539..31808
                     /gene="yacA"
                     /locus_tag="ECO55CA74_RS27165"
                     /old_locus_tag="ECO55CA74_26109"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_015056448.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II toxin-antitoxin system antitoxin YacA"
                     /protein_id="WP_000079946.1"
                     /translation="MAQVNMSLRIDAELKDAFMAAAKSMDRNGSQLIRDFMRQTVERQH
                     NTWFRDQVEAGRQQLGRGDVLPHDMVESSATAWRDEMSRKVAGK"
     gene            31808..32086
                     /gene="yacB"
                     /locus_tag="ECO55CA74_RS27170"
                     /old_locus_tag="ECO55CA74_26114"
     CDS             31808..32086
                     /gene="yacB"
                     /locus_tag="ECO55CA74_RS27170"
                     /old_locus_tag="ECO55CA74_26114"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_013009346.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II toxin-antitoxin system toxin YacB"
                     /protein_id="WP_013009346.1"
                     /translation="MEIFWTMLASQDRKRIREYIAEQNLMAAIELDERIGYSASSLAGQ
                     PYKGRNGRVEGTRELVIHPHFVLVYEVDSQWGKVYVLRVLHTAQKWP"
     gene            complement(32282..32578)
                     /locus_tag="ECO55CA74_RS27175"
                     /old_locus_tag="ECO55CA74_26119"
     CDS             complement(32282..32578)
                     /locus_tag="ECO55CA74_RS27175"
                     /old_locus_tag="ECO55CA74_26119"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000578010.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_001419651.1"
                     /translation="MIIHDIKREMPLKYGLYRVAKWFAWLAHTGIFCTFIIYIGFSIIT
                     QHAGQELPETFKHGFALTFCSFATAALVSQWIGGGLHSKLEERIRMKWQNHAH"
     gene            32923..33510
                     /locus_tag="ECO55CA74_RS27180"
                     /old_locus_tag="ECO55CA74_26124"
     CDS             32923..33510
                     /locus_tag="ECO55CA74_RS27180"
                     /old_locus_tag="ECO55CA74_26124"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000905839.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="serine acetyltransferase"
                     /protein_id="WP_001418189.1"
                     /translation="MLIKNPISYFHIGTFLFSGKKRHLLECWKAEVIMRDKFVFHRLIR
                     NGMQRQRGFLLWWRLANEMYISGNKKQRKCAIKIKNALMAKYGCDIGLGAQIGKGLVLP
                     HHSGVVIHGNVKIGENVIIRQNTTIGEKESDSRENYIVIGDNVDIGAHTCIIGLNVKIG
                     SNVKIGAMSFIMEEVPDNCTYVTRKESRVIMR"
     gene            complement(33792..34385)
                     /locus_tag="ECO55CA74_RS27185"
                     /old_locus_tag="ECO55CA74_26129"
     CDS             complement(33792..34385)
                     /locus_tag="ECO55CA74_RS27185"
                     /old_locus_tag="ECO55CA74_26129"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000517690.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="ProQ/FINO family protein"
                     /protein_id="WP_000517696.1"
                     /translation="MGKNQEERKTPVIVVKKRRTFSPPSLSEKTDIIAPVFTEQTAESA
                     PAGINSSAVETHIPEAPARKKKKKRHRFPRPSHWTREYTHECVEKIKALFPHLRAEGGG
                     FIPLKIGISNDISAFLAESPDTELSMDEWFCAVSCITSRRVYLQRTSVAGVPRYGLDGH
                     PDGQVSETEAQSAVQRLAIIEQRWLRMKERQTEQ"
     gene            34739..36085
                     /gene="yagA"
                     /locus_tag="ECO55CA74_RS27190"
                     /old_locus_tag="ECO55CA74_26134"
     CDS             34739..36085
                     /gene="yagA"
                     /locus_tag="ECO55CA74_RS27190"
                     /old_locus_tag="ECO55CA74_26134"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001132032.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="protein YagA"
                     /protein_id="WP_001132032.1"
                     /translation="MPMILVKKNPRGKVIRELSSEEETAVKTVCGLKRPATMAQHNLAN
                     DLLREMREYDAWLQCDCIPGDSPAMNFAALKNNTGTLYLSSFNHEHAPECPMYRQLSGN
                     EEETSFGASRHPVSTRINYRNFLPPDDSNSVIRLQARSAYHNGERSSVRKKRPRLGRLL
                     LSLIEDAGLNKLDSLANPRIRTNYRECLDAIRQVTLQQEYIRGRALSEIIHFRPGMSER
                     SQERLMETLENSERHWPARRKHMFFQIFMAQHICRDAVEIHWANGNIQVIRPVRGISIN
                     GEAQGGIRPPYWVILAFCRSADGRIICSEGYAHALYQLTCPVPVDSKLERNTLTALLNV
                     ASWLKRKPGTPELSLERPLFDTEVYVNGEKKYVLPDFIVTARAPDGKTARVVIETMGYE
                     DSDYCARKSRQHTGMKQIGVLHTDPPKWLDNDHPPFKKHMYGVFMHLRY"
     gene            36364..38244
                     /locus_tag="ECO55CA74_RS27195"
                     /old_locus_tag="ECO55CA74_26139"
     CDS             36364..38244
                     /locus_tag="ECO55CA74_RS27195"
                     /old_locus_tag="ECO55CA74_26139"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001610315.1"
                     /GO_component="GO:0016020 - membrane [Evidence IEA]"
                     /GO_process="GO:0019835 - cytolysis [Evidence IEA];
                     GO:0050829 - defense response to Gram-negative bacterium
                     [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="colicin Ia central receptor-binding
                     domain-containing protein"
                     /protein_id="WP_001283342.1"
                     /translation="MSDPVRITNPGAESLGYDSDGHEIMAVDIYVNPPRVDVFHGTPPA
                     WSSFGNKTIWGGNEWVDDSPTRSDIEKRDKEITAYKNTLSAQQKENENKRTEAGKRLSA
                     AIAAREKDENTLKTLRAGNADAADITRQEFRLLQAELREYGFRTEIAGYDALRLHTESR
                     MLFADADSLRISPREARSLIEQAEKRQKDAQNADKKAADMLAEYERRKGILDTRLSELE
                     KNGGAALAVLDAQQARLLGQQTRNDRAISEARNKLSSVTESLNTARNALTRAEQQLTQQ
                     KNTPDGKTIVSPEKFPGRSSTNHSIVVSGDPRFAGTIKITTSAVIDNRANLNYLLTHSG
                     LDYKRNILNDRNPVVTEDVEGDKKIYNAEVAEWDKLRQRLLDARNKITSAESAVNSARN
                     NLSARTNEQKHANDALNALLKEKENIRNQLAGINQKIAEEKRKQDELKATKDAINFTTE
                     FLKSVSEKYGAKAEQLAREMAGQAKGKKIRNVEEALKTFEKYRADINKKINAKDRAAIA
                     AALESVKLSDISSNLNRFSRGLGYAGKFTSLADWITEFGKAVRTENWRPLFVKTEAIIA
                     GNAATALVALVFSILTGSALGIIGYGLLMAVTGALIDESLVEKANKFWGI"
     gene            complement(38266..38601)
                     /locus_tag="ECO55CA74_RS27200"
                     /old_locus_tag="ECO55CA74_26144"
     CDS             complement(38266..38601)
                     /locus_tag="ECO55CA74_RS27200"
                     /old_locus_tag="ECO55CA74_26144"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001080726.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="colicin 1A immunity protein"
                     /protein_id="WP_001080734.1"
                     /translation="MNRKYYFNNMWWGWVTGGYMLYMSWDYEFKYRLLFWCISLCGMVL
                     YPVAKWYIEDTALKFTRPDFWNSGFFADTPGKMGLLAVYTGTVFILSLPLSMIYILSVI
                     IKRLSVR"
     gene            38730..39077
                     /locus_tag="ECO55CA74_RS27205"
     CDS             38730..39077
                     /locus_tag="ECO55CA74_RS27205"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001563283.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DUF6404 family protein"
                     /protein_id="WP_000142440.1"
                     /translation="MTFEQKKARAIALMDSKKMWRSNYAPPLLRILWRLGIRLPPLPFM
                     PFWQVTLLMGSLWGISWGCAMWFIYWGPSGMVAGEAIIISITGGFLFGLLMASFHWWRR
                     KVNLLPPWDDV"
     gene            complement(39095..39685)
                     /locus_tag="ECO55CA74_RS27210"
     CDS             complement(39095..39685)
                     /locus_tag="ECO55CA74_RS27210"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001545742.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_000194567.1"
                     /translation="MTQSRRPSPLQRRVLIVLAALDEKRPGPVLTRDLERGLERSGEAP
                     VYGPNLRASCRRLEDAGWLRTLRAPNLQLAVELTDAGRAVAQPLLLAEQDRLRAEQRAA
                     EVVVLPLVPEAGLPADGTSATDLAVELNGMTYQACRGDFVVRLDGSTCLQLWNKEGRVV
                     RLEGDPLEVAQWLQACHDAGMEVRVQVNESVTP"
     gene            complement(39805..40446)
                     /locus_tag="ECO55CA74_RS27215"
                     /old_locus_tag="ECO55CA74_26149"
     CDS             complement(39805..40446)
                     /locus_tag="ECO55CA74_RS27215"
                     /old_locus_tag="ECO55CA74_26149"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001722340.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="recombinase family protein"
                     /protein_id="WP_000470626.1"
                     /translation="MFIRAYLRASTEDQFADRAKEMLEQFVQGRGHKIASYYRENISGT
                     KLDRPELGRLLMDSHRNDILLVEQIDRLTRLSNSDWITLKKQIEQHELRIVSLDVPTSW
                     QALSDKAPSQSDPITRAVITAINNMLIDLMAAMSHKDWLSRRQRQKQGIERAHTLGKYR
                     GKQADQERHQKVLYYRQVKKLSIRETADATGYSTSQVCRIQALYREPTTD"
     gene            40601..43579
                     /locus_tag="ECO55CA74_RS27220"
                     /old_locus_tag="ECO55CA74_26154"
     CDS             40601..43579
                     /locus_tag="ECO55CA74_RS27220"
                     /old_locus_tag="ECO55CA74_26154"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_003935408.1"
                     /GO_function="GO:0004803 - transposase activity [Evidence
                     IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="Tn3-like element TnEc1 family transposase"
                     /protein_id="WP_000124031.1"
                     /translation="MARRQILSQSERESLLALPDDELTLTRMAYFSEHDLALINAHRKP
                     ASRFGFAVLLCYLKNVGFAPDKKTPPSDALLKPIANRLKLADGLWSSYINGRETTRREH
                     LTELYRYLGVKAFTNKIQQSCITHLLPMATRTDKGILLAEEMLAYLRQNKVMFPAIDVV
                     ERTCAEAMAGGDKIVFQTLNAPLTSAHREALDRLLESSDNQPSRLTWLLQPPGKINGKN
                     VLQHIDRLNSIESLALPEGIDRTIHQNRLLKLAREGRKMSSRDLTRFSAARRHAILVCV
                     LEDARATLTDEIIELHERILNSLFNKAKKTQAERLQQTGRLIQLKLKQYIDIGQALSEA
                     HDSGEDPWLAIEKILPWPEFIASLEETRHLARKNNFDPLHIITEKYSTLRKYAPRMLST
                     LQLVATPAAQALADALLVIKDMYKKQLRKVPATAPLEFVPESWRKVVITPTGIDRQYYE
                     FCALSELKGALRSGDIWVKGSRRYKNFDDYLIPEKDFDKLSPALPLPVSADYHEYITNR
                     MILLQSKLEEVNKMAAHGELPDVEISDKGVKISPLDNCVPLQVSPLSELIYSMLPRPKI
                     TEILDEVNSWTAFTRHFSHIKNDMTRPDTRLLLTTILADGINLGLTKMAEACPGCTKSS
                     LEDIQAWYIRDETYSAALAELVNAQGKRPLAAFWGDGTTSSSDGQNFRTGNSGRYAGQI
                     NPKYGQEPGCQFYTHISDQYSPFYTCIISRVRDSTHVLDGLLYHESDLDIREHYTDTAG
                     FTDHVFALMHLLGFAFCPRIRDLHDKKLFIKGKADQYPALHSLISPTRINLKEIEIHWR
                     EVLRLATSIKQGTVTASLMLRKLASYPKQNGLAKALREIGRIERTLFMLDWFRDPALRR
                     RVQAGLNKGEARNALARAVFMHRLGEIRDRKPENQSYRASGLTLLTAAISLWNTVYMER
                     AVDALKRKGMKINAQLLSHLSPLGWEHINLTGDYIWKNNRIPTSGKFRRLRSVKIDKVK
                     KQP"
     gene            43657..44061
                     /locus_tag="ECO55CA74_RS27225"
                     /old_locus_tag="ECO55CA74_26159"
     CDS             43657..44061
                     /locus_tag="ECO55CA74_RS27225"
                     /old_locus_tag="ECO55CA74_26159"
                     /inference="COORDINATES: protein motif:HMM:NF013677.2"
                     /GO_function="GO:0003677 - DNA binding [Evidence IEA];
                     GO:0004803 - transposase activity [Evidence IEA]"
                     /GO_process="GO:0006313 - transposition, DNA-mediated
                     [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="transposase"
                     /protein_id="WP_000839179.1"
                     /translation="MKSLTAVRKKSPNYPVEFKIKMVELSHRPEISVAQLAREHGINDN
                     LLFKWRQYWREGKLRPPSTTENNVPELLPITLDAEDVVPTTSPRSQPVAAATPESLNIS
                     CEVTFRHGSLRLNGAISENILNLLIRELKR"
     gene            44058..44405
                     /gene="tnpB"
                     /locus_tag="ECO55CA74_RS27230"
                     /old_locus_tag="ECO55CA74_26164"
     CDS             44058..44405
                     /gene="tnpB"
                     /locus_tag="ECO55CA74_RS27230"
                     /old_locus_tag="ECO55CA74_26164"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_004966400.1"
                     /note="TnpB, as the term is used for proteins encoded by
                     IS66 family insertion elements, is considered an accessory
                     protein, since TnpC, encoded by a neighboring gene, is a
                     DDE family transposase; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="IS66 family insertion sequence element accessory
                     protein TnpB"
                     /protein_id="WP_000612550.1"
                     /translation="MIPLPSGTKIWLVAGITDMRNGFNGLAAKMQTTLKDDPMSGHVFI
                     FRGRNGSQVKLLWSTGDGLCLLTKRLERGRFAWPSARDGKVFLTPAQLAMLLEDIDWRQ
                     PKRLLTSLTML"
     gene            44454..45992
                     /locus_tag="ECO55CA74_RS27235"
                     /old_locus_tag="ECO55CA74_26169"
     CDS             44454..45992
                     /locus_tag="ECO55CA74_RS27235"
                     /old_locus_tag="ECO55CA74_26169"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000099160.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="IS66-like element ISEc22 family transposase"
                     /protein_id="WP_000099187.1"
                     /translation="MSSSLPDDINALKRLLAEQEALNRALLEKLNEREREIDHLQAQLD
                     KLRRMNFGSRSEKVSRRIAQMEADLKALQKESDTLTGRVDDPTVQRPLRQTRTRKPFPE
                     SLPRDEKRLLPAASCCPECGGSLSYLGEDAAEQLELIRSAFRVIRTVREKHACTQCDAI
                     VQAPAPSRPIERGIAGPGLLARVLISKYAEHTPLYRQSEMYGRQGVELSRSLLSGWVDA
                     CCRLLSPLEEALQDYVLTDGKLHADDTPVPVLLPGNKKTKTGRLWTYVRDDRNAGSTLV
                     PAVWFAYSPDRKGIHPQPHLAGFSGVLQADAYAGFNELYRDGRITEAACWAHARRKIHD
                     VHVRTPSALTEEALKRIGELYAIEAEIRGMTAEQRLAERQLKTKPLLKSLESWLREKMK
                     TLSRHSELAKAFAYALNQWPALTYYADDGWAEADNNIAENALRMVSLGRKNYLFFGSDH
                     GGERGALLYSLIGTCKLNGVEPESYLRYVLDVIADWPINRVGELLPWRVALPTE"
     gene            46074..46514
                     /locus_tag="ECO55CA74_RS29860"
     CDS             46074..46514
                     /locus_tag="ECO55CA74_RS29860"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001340790.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="recombinase family protein"
                     /protein_id="WP_072141484.1"
                     /translation="MIVWKLDRLGRSLSHLLRIIEDLKIRGIAFRSLTESIDTTTPHGS
                     FLFNLFGTLAEYERTLITERVNAGLAATLRRGRKGGRPPAIDAERVDQILAALEGGASK
                     ASVCRAFSVLRSTLTDTLRRIGWAGPGGRNLTTDQSNVISRR"
     gene            46495..47247
                     /locus_tag="ECO55CA74_RS27240"
                     /old_locus_tag="ECO55CA74_26174"
     CDS             46495..47247
                     /locus_tag="ECO55CA74_RS27240"
                     /old_locus_tag="ECO55CA74_26174"
                     /inference="COORDINATES: protein motif:HMM:NF025079.2"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DUF4158 domain-containing protein"
                     /protein_id="WP_001418914.1"
                     /translation="MSFLDAKSYDTLFGLPELYEDALPRFSLSCEDIAFARTHRRSHNR
                     LGFAIQLALVRDLGRTLRTGEIPPEAVISVVAEQLDIYPAVFTLYAQREETRREHAREI
                     VSALELRSVQSSDYRMLIIAATREAATTEKGLPITRAVINKLKDQKLLAPAPAQLIRLA
                     MAGRADARRLSYRELIRDLKPSSISALEQLLTERVGEKSILGWIAEAPEGVKLKNLKGL
                     IARLEVLRTAAISDVTNGAIVIHTQHLK"
     gene            47288..>48031
                     /gene="istA"
                     /locus_tag="ECO55CA74_RS27245"
                     /old_locus_tag="ECO55CA74_26179"
                     /pseudo=""
     CDS             47288..>48031
                     /gene="istA"
                     /locus_tag="ECO55CA74_RS27245"
                     /old_locus_tag="ECO55CA74_26179"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000627495.1"
                     /GO_function="GO:0004803 - transposase activity [Evidence
                     IEA]"
                     /note="incomplete; partial in the middle of a contig;
                     missing C-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="IS21 family transposase"
     gene            <48168..48832
                     /locus_tag="ECO55CA74_RS27250"
                     /pseudo=""
     CDS             <48168..48832
                     /locus_tag="ECO55CA74_RS27250"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000533644.1"
                     /GO_function="GO:0003677 - DNA binding [Evidence IEA]"
                     /GO_process="GO:0015074 - DNA integration [Evidence IEA];
                     GO:0006310 - DNA recombination [Evidence IEA]"
                     /note="frameshifted; internal stop; incomplete; partial in
                     the middle of a contig; missing N-terminus; Derived by
                     automated computational analysis using gene prediction
                     method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="tyrosine-type recombinase/integrase"
     gene            49555..50880
                     /gene="nleA"
                     /locus_tag="ECO55CA74_RS27255"
                     /old_locus_tag="ECO55CA74_26189"
     CDS             49555..50880
                     /gene="nleA"
                     /locus_tag="ECO55CA74_RS27255"
                     /old_locus_tag="ECO55CA74_26189"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_309839.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type III secretion system effector NleA"
                     /protein_id="WP_001025657.1"
                     /translation="MNIQPIVQSGITTQNNQHNQAEQAPPAQIPQSELPNGCEAGFVVH
                     IPDDIQQHAPECGERTALLSLIQDEGLLSGLDKYLAPHLEEGSAGKKALDMFGLFNVTQ
                     MALEIPSTVRGISGKYGVQMNIVKPDIHPTSGNYFLQIFPLHDEIGLNFKDLPGPLKNA
                     LSNINISTTAVSAITSAATSATTSTVTTEPKDPIPWFGLTAQVVRNHGVELPIVKTENG
                     WKLVGETPLTPDGPKANYTEEWVIRPGEADFKYGTSPLQATLGLEFGAHFKWDLDNPNT
                     KYAVLTNAAANALGAAGGFAVSKIPGVDPMLAPHIGAMVGQAAGHAIQCNTPGLKPDTI
                     LWWAGTTLGLADLNKAETGEARFTDYPRIWWHAREGAIFPNKEDIARATGADIRAMEEG
                     VPVGQSHPRPEDVVINIESNDLPHHNPLNHVDIVDIIQETRV"
     gene            51029..51312
                     /locus_tag="ECO55CA74_RS29865"
                     /pseudo=""
     CDS             51029..51312
                     /locus_tag="ECO55CA74_RS29865"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_414822.1"
                     /note="frameshifted; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="YkgJ family cysteine cluster protein"
     gene            complement(51867..53080)
                     /locus_tag="ECO55CA74_RS27270"
                     /old_locus_tag="ECO55CA74_26204"
     CDS             complement(join(51867..52789,52789..53080))
                     /locus_tag="ECO55CA74_RS27270"
                     /old_locus_tag="ECO55CA74_26204"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_086558238.1"
                     /ribosomal_slippage=""
                     /GO_function="GO:0004803 - transposase activity [Evidence
                     IEA]"
                     /note="programmed frameshift; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="IS3 family transposase"
                     /protein_id="WP_165382802.1"
                     /translation="MTKNTRFSPEVRQRAARMVLESQGEYDSQWATICSIAPKIGCTPE
                     TLRVWVRQHERDTGGGDGGLTTAERQRLKELERENRELRRSNDILRQASAYFGEGGVRP
                     PLEKMMPLLDKLREQYGVGPLCSELHIAPSTYYHCQQQRHHPDKRSARAQRDDWLKKEI
                     QRVYDENHKVYGVRKVWRQLLREGIRVARCTVARLMAVMGLAGVLRGKKVRTTISRKAV
                     AAGDRVNRQFVAERPDQLWVADFTYVSTWQGFVYVAFIIDVFAGYIVGWRVSSSMETTF
                     VLDALEQVLWARRPSGTVHHSDKGSQYVSLAYTQRLKEAGLLASTGSTGDSYDNAMAES
                     INGLYKAEVIHRKSWKNRAEVELATLTWVDWYNNRRLLERLGHTPPAEAEKAYYASIGN
                     DDLAA"
     misc_feature    complement(52683..52799)
                     /locus_tag="ECO55CA74_RS27270"
                     /old_locus_tag="ECO55CA74_26204"
                     /inference="COORDINATES: nucleotide
                     motif:Rfam:14.4:RF01497"
                     /inference="COORDINATES: profile:INFERNAL:1.1.1"
                     /note="AL1L pseudoknot; Derived by automated computational
                     analysis using gene prediction method: cmsearch."
                     /db_xref="RFAM:RF01497"
     gene            complement(53183..53620)
                     /locus_tag="ECO55CA74_RS27280"
                     /old_locus_tag="ECO55CA74_26214"
     CDS             complement(53183..53620)
                     /locus_tag="ECO55CA74_RS27280"
                     /old_locus_tag="ECO55CA74_26214"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000273581.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_000273581.1"
                     /translation="MYFIGYHGTSEASAQNILSVGVQERFLPPTGQIGRGFYIAKMNGT
                     LPQWGAENATELARRNQPYFTRMVSLLTGESNNPWLDKAAQRTILKIYTVRPLLHCKWN
                     IMNPGDLEFLKATLYDNGGPGLDLKRDCKWLYHQRNSSTCG"
     gene            complement(53869..54048)
                     /locus_tag="ECO55CA74_RS27285"
                     /old_locus_tag="ECO55CA74_26219"
     CDS             complement(53869..54048)
                     /locus_tag="ECO55CA74_RS27285"
                     /old_locus_tag="ECO55CA74_26219"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000526857.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_000526857.1"
                     /translation="MGNILFDEKNNRFWLIDFSNSYEHYYSIDKDSKLFVNEMADREFC
                     SILKTLRENAISNI"
     gene            54272..54625
                     /locus_tag="ECO55CA74_RS27290"
                     /old_locus_tag="ECO55CA74_26224"
     CDS             54272..54625
                     /locus_tag="ECO55CA74_RS27290"
                     /old_locus_tag="ECO55CA74_26224"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001368923.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_001368923.1"
                     /translation="MRQVLNINVGLGSDIPAGHSPSIFEACLHAITASKALNDGGNSQL
                     SSEVWGYSGASVSFREAFWLATGGDGKILDLPIGKLRKDYFVDTIVIDTNGHNLDIIIY
                     DDTTEDILQKLII"
     gene            complement(54835..>55097)
                     /locus_tag="ECO55CA74_RS32555"
                     /pseudo=""
     CDS             complement(54835..>55097)
                     /locus_tag="ECO55CA74_RS32555"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_004385766.1"
                     /note="frameshifted; incomplete; partial in the middle of a
                     contig; missing N-terminus; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="epoxyqueuosine reductase QueH"
     gene            <55169..>55288
                     /locus_tag="ECO55CA74_RS27730"
                     /pseudo=""
     CDS             <55169..>55288
                     /locus_tag="ECO55CA74_RS27730"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_958721.1"
                     /note="incomplete; partial in the middle of a contig;
                     missing N-terminus and C-terminus; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="serine/threonine protein kinase"
     gene            55412..56152
                     /locus_tag="ECO55CA74_RS27300"
                     /old_locus_tag="ECO55CA74_26234"
     CDS             55412..56152
                     /locus_tag="ECO55CA74_RS27300"
                     /old_locus_tag="ECO55CA74_26234"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052628.1"
                     /GO_function="GO:0003677 - DNA binding [Evidence IEA]"
                     /GO_process="GO:0015074 - DNA integration [Evidence IEA];
                     GO:0006310 - DNA recombination [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="tyrosine-type recombinase/integrase"
                     /protein_id="WP_001066926.1"
                     /translation="MNNVIPLQNSPERVSLLPIAPGVDFATALSLRRMATSTGATPAYL
                     LAPEVSALLFYMPDQRHHMLFATLWNTGMRIGEARMLTPESFDLDGARPFVRILSEKVR
                     ARRGRPPKDEVRLVPLTDISYVRQMESWMITTRPRRREPLWAVTDETMRNWLKQAVRRA
                     EADGVHFSIPVTPHTFRHSYIMHMLYHRQPRKVIQALAGHRDPRSMEVYTRVFALDMAA
                     TLAVPFTGDGRDAAEILRTLPPLR"
     gene            complement(56436..57413)
                     /locus_tag="ECO55CA74_RS27305"
     CDS             complement(56436..57413)
                     /locus_tag="ECO55CA74_RS27305"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052630.2"
                     /GO_function="GO:0003887 - DNA-directed DNA polymerase
                     activity [Evidence IEA]"
                     /GO_process="GO:0006270 - DNA replication initiation
                     [Evidence IEA]"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="RepB family plasmid replication initiator
                     protein"
                     /protein_id="WP_000361616.1"
                     /translation="MDKSSGELVTLTPNNNNTVQPVALMRLGVFVPTLKSLKNSKKNTL
                     SRTDATEELTRLSLARAEGFDKVEITGPRLDMDNDFKTWVGIIHSFARHNVTGDKVELP
                     FVEFAKLCGIPSNQSSRRLRERISPSLKRIAGTVISFSRTDEKHTREYITHLVQSAYYD
                     TERDIVQLQADPRLFELYQFDRKVLLQLKAINALKRRESAQALYTFIESLPRDPAPISL
                     ARLRARLNLKSPVFSQNQTVRRAMEQLREIGYLDYTEIQRGRTKLFCIHYRRPRLKAPN
                     DESKENPLPPSPAEKVSPEIAEKLALLEKLGITLDDLEKLFKSR"
     gene            complement(58059..>58464)
                     /locus_tag="ECO55CA74_RS29885"
                     /pseudo=""
     CDS             complement(58059..>58464)
                     /locus_tag="ECO55CA74_RS29885"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_086558235.1"
                     /GO_process="GO:0015074 - DNA integration [Evidence IEA]"
                     /note="frameshifted; incomplete; partial in the middle of a
                     contig; missing N-terminus; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="integrase core domain-containing protein"
     gene            complement(58466..58753)
                     /locus_tag="ECO55CA74_RS27315"
                     /old_locus_tag="ECO55CA74_26249"
     CDS             complement(58466..58753)
                     /locus_tag="ECO55CA74_RS27315"
                     /old_locus_tag="ECO55CA74_26249"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_020317119.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II toxin-antitoxin system RelE/ParE family
                     toxin"
                     /protein_id="WP_001270421.1"
                     /translation="MRYQVKFREDALKEWQKLDKTIQQQFAKKLKKCCDNPHIPSAKLR
                     GIKDCYKIKLRASGFRLVYQVIDEQLIIAVVAVGKRERSDVYNLASERMR"
     gene            complement(58750..59001)
                     /locus_tag="ECO55CA74_RS27320"
                     /old_locus_tag="ECO55CA74_26254"
     CDS             complement(58750..59001)
                     /locus_tag="ECO55CA74_RS27320"
                     /old_locus_tag="ECO55CA74_26254"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_001595120.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="type II toxin-antitoxin system Phd/YefM family
                     antitoxin"
                     /protein_id="WP_001132893.1"
                     /translation="MPNIILSDTSASVSELKKNPMATVSAGDGFPIAILNRNQPAFYCV
                     PAELYEKMLDALDDQELVKLVAERSNQPLHDVDLDKYL"
     gene            59390..60595
                     /locus_tag="ECO55CA74_RS27325"
                     /old_locus_tag="ECO55CA74_26259"
     CDS             59390..60595
                     /locus_tag="ECO55CA74_RS27325"
                     /old_locus_tag="ECO55CA74_26259"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000817637.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="AAA family ATPase"
                     /protein_id="WP_000817637.1"
                     /translation="MKRDYGSVGTIALRASALLQAMSRDIEEQRKEFNLTEYHQTYTRN
                     AVAKLPKLSRRIVELAIKEMEESGYEFNKKRVGNVEQYALTIQNVIDIYAHRQIPKYRD
                     VHKEPYVIFVVNLKGGVSKTVSTVTLAHALRVHPDLLRHDLRILVIDLDPQASSTMFLD
                     HTHSIGTVLETAAQAMLNNLDAETLREAVIRPTMIPGVDVIPASIDDGFVASQWESLVA
                     EHLPGFKPSEVLRKTIIDRIADDYDFVFIDTGPHLDPFLLNGLAASDLLLTPTPPAQVD
                     FHSTLKYLTRLPEMLERLEEEGVEPRLSASIGFMSKMTSKRDHETSHSLAREVYASNIL
                     DSSLPRLDGFERCGESFDTIISANPVSYPGSAEALKKARTEAERFTKAVFDRIEYIRGA
                     SK"
     gene            60592..61554
                     /locus_tag="ECO55CA74_RS27330"
                     /old_locus_tag="ECO55CA74_26264"
     CDS             60592..61554
                     /locus_tag="ECO55CA74_RS27330"
                     /old_locus_tag="ECO55CA74_26264"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:WP_000756322.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="ParB family protein"
                     /protein_id="WP_000756329.1"
                     /translation="MKKVLARGRVLGNSNSEFARMLEGDGEIKTFTLKSGKQAKFIKTV
                     VLSGDIESKTFVDVSVNGRDQTMLSRESVSDITRTIKLQQFFPAIGREVDGRIEVLDGT
                     RRRAACIYNNVKFEILVTKDSIDIADARQLAKDIQTAREHSLRELGKRLEVTYGASMTK
                     EEIAQAESISPAKVTRAFQAASVPDEMISVFPIINDISLSDYQFLLKLSEKATNKKMSV
                     EEFMDRVRQKLMALPDYPTIEKSKILAVFRSEGKLLTDRPVKTVETEKLKEFSDRNQFA
                     RKKTDPRKRLVVYEFSRISNEVQLEIDEAIKNILRKLPE"
     gene            complement(61695..62814)
                     /locus_tag="ECO55CA74_RS27335"
                     /pseudo=""
     CDS             complement(61695..62814)
                     /locus_tag="ECO55CA74_RS27335"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_490544.1"
                     /note="frameshifted; internal stop; Derived by automated
                     computational analysis using gene prediction method:
                     Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="DUF4113 domain-containing protein"
     gene            <62737..63153
                     /locus_tag="ECO55CA74_RS27340"
                     /old_locus_tag="ECO55CA74_26279"
                     /pseudo=""
     CDS             <62737..63153
                     /locus_tag="ECO55CA74_RS27340"
                     /old_locus_tag="ECO55CA74_26279"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052643.1"
                     /note="incomplete; partial in the middle of a contig;
                     missing N-terminus; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
     gene            63157..63462
                     /locus_tag="ECO55CA74_RS30775"
     CDS             63157..63462
                     /locus_tag="ECO55CA74_RS30775"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052644.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_032163448.1"
                     /translation="MTETGGQPPVSFPVKDVAGLLFLLRRLTRRGRNAACGQCPASGRA
                     RDGRFYRSRLALVTVYASPSPFSDERPSSRFRGISSPSKRRRLRYSTVGLTRYRTR"
     gene            63539..64222
                     /locus_tag="ECO55CA74_RS27350"
                     /old_locus_tag="ECO55CA74_26284"
     CDS             63539..64222
                     /locus_tag="ECO55CA74_RS27350"
                     /old_locus_tag="ECO55CA74_26284"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052645.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DNA methylase"
                     /protein_id="WP_000085942.1"
                     /translation="MSRFIQGDCVRVMATFPGNAVDFILTDPPYLVGFRDRQGRTIAGD
                     KTDEWLQPACNEMYRVLKKDTLMVSFYGWNRVDRFMAAWKNAGFSVVGHLVFTKTYTSK
                     AAYVGYRHECAYILAKGRPALPQKPLPDVLGWKYSGNRHHPTEKPVTSLQPLIESFTHP
                     NAIVLDPFAGSGSTCVAALQSGRRYIGIELLEQYHRAGQQRLAAVQRAMQQGAANDNWF
                     EPEAA"
     gene            64223..64444
                     /locus_tag="ECO55CA74_RS27355"
                     /old_locus_tag="ECO55CA74_26289"
     CDS             64223..64444
                     /locus_tag="ECO55CA74_RS27355"
                     /old_locus_tag="ECO55CA74_26289"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_858332.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="WP_001104880.1"
                     /translation="MNYAGHEKLRAEVAEVANAMCDLRTTMNEMEQRYSFNADTLPERL
                     VRQTLFRANRLLMEAYTEILELDSCFKD"
     gene            64404..64890
                     /locus_tag="ECO55CA74_RS27360"
                     /old_locus_tag="ECO55CA74_26294"
                     /pseudo=""
     CDS             64404..64890
                     /locus_tag="ECO55CA74_RS27360"
                     /old_locus_tag="ECO55CA74_26294"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052646.1"
                     /note="frameshifted; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="DUF1380 family protein"
     gene            64936..65712
                     /locus_tag="ECO55CA74_RS32075"
                     /pseudo=""
     CDS             64936..65712
                     /locus_tag="ECO55CA74_RS32075"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_052647.1"
                     /note="internal stop; Derived by automated computational
                     analysis using gene prediction method: Protein Homology."
                     /pseudo=""
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
CONTIG      join(CP003111.1:1..66078)
//
