LOCUS       NC_017634            4747819 bp    DNA     circular CON 23-FEB-2023
DEFINITION  Escherichia coli O83:H1 str. NRG 857C, complete sequence.
ACCESSION   NC_017634
VERSION     NC_017634.1
DBLINK      BioProject: PRJNA224116
            BioSample: SAMN02603727
            Assembly: GCF_000183345.1
KEYWORDS    RefSeq.
SOURCE      Escherichia coli O83:H1 str. NRG 857C
  ORGANISM  Escherichia coli O83:H1 str. NRG 857C
            Bacteria; Pseudomonadota; Gammaproteobacteria; Enterobacterales;
            Enterobacteriaceae; Escherichia.
REFERENCE   1  (bases 1 to 4747819)
  AUTHORS   Nash,J.H., Villegas,A., Kropinski,A.M., Aguilar-Valenzuela,R.,
            Konczy,P., Mascarenhas,M., Ziebell,K., Torres,A.G., Karmali,M.A. and
            Coombes,B.K.
  TITLE     Genome sequence of adherent-invasive Escherichia coli and
            comparative genomic analysis with other E. coli pathotypes
  JOURNAL   BMC Genomics 11, 667 (2010)
   PUBMED   21108814
  REMARK    Publication Status: Online-Only
REFERENCE   2  (bases 1 to 4747819)
  AUTHORS   Eaves-Pyles,T., Allen,C.A., Taormina,J., Swidsinski,A., Tutt,C.B.,
            Jezek,G.E., Islas-Islas,M. and Torres,A.G.
  TITLE     Escherichia coli isolated from a Crohn's disease patient adheres,
            invades, and induces inflammatory responses in polarized intestinal
            epithelial cells
  JOURNAL   Int J Med Microbiol 298 (5-6), 397-409 (2008)
   PUBMED   17900983
REFERENCE   3  (bases 1 to 4747819)
  AUTHORS   Allen,C.A., Niesel,D.W. and Torres,A.G.
  TITLE     The effects of low-shear stress on Adherent-invasive Escherichia
            coli
  JOURNAL   Environ Microbiol 10 (6), 1512-1525 (2008)
   PUBMED   18312396
REFERENCE   4  (bases 1 to 4747819)
  AUTHORS   Boerlin,P., Coombes,B., Karmali,M., Konczy,P., Kropinski,A.,
            Mascarenhas,M., Nash,J., Swidsinski,A., Torres,A., Villegas,A. and
            Ziebell,K.
  TITLE     Direct Submission
  JOURNAL   Submitted (07-JAN-2010) Laboratory for Foodborne Zoonoses, Public
            Health Agency of Canada, 110 Stone Road West, Guelph, Ontario N1G
            3W4, Canada
COMMENT     ##Genome-Annotation-Data-START##
            Annotation Provider               :: NCBI RefSeq
            Annotation Date                   :: 02/23/2023 08:59:32
            Annotation Pipeline :: NCBI Prokaryotic Genome Annotation Pipeline
            (PGAP)
            Annotation Method :: Best-placed reference protein set; GeneMarkS-2+
            Annotation Software revision      :: 6.4
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA
            Genes (total)                     :: 4,752
            CDSs (total)                      :: 4,641
            Genes (coding)                    :: 4,499
            CDSs (with protein)               :: 4,499
            Genes (RNA)                       :: 111
            rRNAs                             :: 8, 7, 7 (5S, 16S, 23S)
            complete rRNAs                    :: 8, 7, 7 (5S, 16S, 23S)
            tRNAs                             :: 83
            ncRNAs                            :: 6
            Pseudo Genes (total)              :: 142
            CDSs (without protein)            :: 142
            Pseudo Genes (ambiguous residues) :: 0 of 142
            Pseudo Genes (frameshifted)       :: 53 of 142
            Pseudo Genes (incomplete)         :: 96 of 142
            Pseudo Genes (internal stop)      :: 24 of 142
            Pseudo Genes (multiple problems)  :: 29 of 142
            Pseudo Genes (short protein)      :: 3 of 142
            CRISPR Arrays                     :: 2
            ##Genome-Annotation-Data-END##
            REFSEQ INFORMATION: The reference sequence is identical to
            CP001855.1.
            Bacterium available from Laboratory for Foodborne Zoonoses, 110
            Stone Road West, Guelph, Ontario N1G 3W4, Canada
            Genome was manually curated based on annotation generated by the
            NCBI Prokaryotic Genomes Automatic Annotation Pipeline Group.
            Information about the Pipeline can be found here:
            http://www.ncbi.nlm.nih.gov/genomes/static/Pipeline.html.
            The annotation was added by the NCBI Prokaryotic Genome Annotation
            Pipeline (PGAP). Information about PGAP can be found here:
            https://www.ncbi.nlm.nih.gov/genome/annotation_prok/
            COMPLETENESS: full length.
FEATURES             Location/Qualifiers
     source          1..4747819
                     /organism="Escherichia coli O83:H1 str. NRG 857C"
                     /mol_type="genomic DNA"
                     /strain="NRG 857C"
                     /serotype="O83:H1"
                     /db_xref="taxon:685038"
                     /note="strain associated with Crohn's Disease; AIEC O83:H1"
CONTIG      join(CP001855.1:1..4747819)
//
